- id: command
  language: python
  name: Command
  entry: pre-commit-command
  pass_filenames: false
- id: shell
  language: script
  name: Shell Script
  entry: pre-commit-shell
  pass_filenames: false
